---
name: CI

on:
  push:
    paths-ignore:
      - "**/README.md"
  pull_request:
    branches: [main]
    paths-ignore:
      - "**/README.md"
  schedule:
    - cron: "50 7 * * *"

jobs:
  build-projects:
    name: Build ${{ matrix.target }}-${{ matrix.env }}-${{ matrix.project }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        env: ["std", "no_std"]
        target: ["esp32", "esp32s2", "esp32s3", "esp32c3"]
        project: ["blinky", "template"]
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Pull Docker image (std)
        if: matrix.env == 'std'
        run: docker image pull wokwi/builder-rust-std-${{ matrix.target }}

      - name: Pull Docker image (no_std)
        if: matrix.env == 'no_std'
        run: docker image pull wokwi/builder-rust-nostd-esp

      - name: Test code example in Docker image (std)
        if: matrix.env == 'std'
        uses: addnab/docker-run-action@v3
        with:
          image: wokwi/builder-rust-std-${{ matrix.target }}
          options: -u esp -v ${{ github.workspace }}:/home/esp/workspace
          run: |
            export IDF_PATH=/home/esp/.espressif/frameworks/esp-idf-release-v4.4
            . /home/esp/export-esp.sh
            cat /home/esp/workspace/${{ matrix.target }}-${{ matrix.env }}-${{ matrix.project }}/main.rs > rust-project/src/main.rs
            cd rust-project
            cargo build --release

      - name: Test code example in Docker image (no_std)
        if: matrix.env == 'no_std'
        uses: addnab/docker-run-action@v3
        with:
          image: wokwi/builder-rust-nostd-esp
          options: -u esp -v ${{ github.workspace }}:/home/esp/workspace
          run: |
            . /home/esp/export-esp.sh
            cat /home/esp/workspace/${{ matrix.target }}-no_std-${{ matrix.project }}/main.rs > rust-project-${{ matrix.target }}/src/main.rs
            cat /home/esp/workspace/${{ matrix.target }}-no_std-${{ matrix.project }}/Cargo.toml > rust-project-${{ matrix.target }}/Cargo.toml
            cd rust-project-${{ matrix.target }}
            cargo build --release
